[build]
command = "npm install"
publish = "public"
functions = "netlify/functions"

[[functions]]
name = "app"
node_bundler = "zisi"
included_files = ["node_modules/**"]

[dev]
command = "npm run dev"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200
